#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDPCheck
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EDPCheck")]
	public partial class EDPDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertT_ST(T_ST instance);
    partial void UpdateT_ST(T_ST instance);
    partial void DeleteT_ST(T_ST instance);
    #endregion
		
		public EDPDataDataContext() : 
				base(global::EDPCheck.Properties.Settings.Default.EDPCheckConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EDPDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDPDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDPDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDPDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_ErrMsg> T_ErrMsg
		{
			get
			{
				return this.GetTable<T_ErrMsg>();
			}
		}
		
		public System.Data.Linq.Table<T_Err> T_Err
		{
			get
			{
				return this.GetTable<T_Err>();
			}
		}
		
		public System.Data.Linq.Table<T_ST> T_ST
		{
			get
			{
				return this.GetTable<T_ST>();
			}
		}
		
		public System.Data.Linq.Table<T_Msg> T_Msg
		{
			get
			{
				return this.GetTable<T_Msg>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_ErrMsg")]
	public partial class T_ErrMsg
	{
		
		private int _ErrMsgID;
		
		private int _ST;
		
		private string _ErrMsg;
		
		private System.DateTime _ErrTime;
		
		public T_ErrMsg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrMsgID", DbType="Int NOT NULL")]
		public int ErrMsgID
		{
			get
			{
				return this._ErrMsgID;
			}
			set
			{
				if ((this._ErrMsgID != value))
				{
					this._ErrMsgID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST", DbType="Int NOT NULL")]
		public int ST
		{
			get
			{
				return this._ST;
			}
			set
			{
				if ((this._ST != value))
				{
					this._ST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrMsg", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ErrMsg
		{
			get
			{
				return this._ErrMsg;
			}
			set
			{
				if ((this._ErrMsg != value))
				{
					this._ErrMsg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrTime", DbType="DateTime NOT NULL")]
		public System.DateTime ErrTime
		{
			get
			{
				return this._ErrTime;
			}
			set
			{
				if ((this._ErrTime != value))
				{
					this._ErrTime = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Err")]
	public partial class T_Err
	{
		
		private int _ERRID;
		
		private int _ST;
		
		private string _MacName;
		
		private string _MacIP;
		
		private System.DateTime _ErrTime;
		
		private System.Nullable<System.DateTime> _ReTime;
		
		public T_Err()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERRID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ERRID
		{
			get
			{
				return this._ERRID;
			}
			set
			{
				if ((this._ERRID != value))
				{
					this._ERRID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST", DbType="Int NOT NULL")]
		public int ST
		{
			get
			{
				return this._ST;
			}
			set
			{
				if ((this._ST != value))
				{
					this._ST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MacName
		{
			get
			{
				return this._MacName;
			}
			set
			{
				if ((this._MacName != value))
				{
					this._MacName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacIP", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string MacIP
		{
			get
			{
				return this._MacIP;
			}
			set
			{
				if ((this._MacIP != value))
				{
					this._MacIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrTime", DbType="DateTime NOT NULL")]
		public System.DateTime ErrTime
		{
			get
			{
				return this._ErrTime;
			}
			set
			{
				if ((this._ErrTime != value))
				{
					this._ErrTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReTime
		{
			get
			{
				return this._ReTime;
			}
			set
			{
				if ((this._ReTime != value))
				{
					this._ReTime = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_ST")]
	public partial class T_ST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STID;
		
		private string _ST;
		
		private string _Address;
		
		private System.Nullable<System.DateTime> _LastTime;
		
		private string _dd;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTIDChanging(int value);
    partial void OnSTIDChanged();
    partial void OnSTChanging(string value);
    partial void OnSTChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnLastTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastTimeChanged();
    partial void OnddChanging(string value);
    partial void OnddChanged();
    #endregion
		
		public T_ST()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int STID
		{
			get
			{
				return this._STID;
			}
			set
			{
				if ((this._STID != value))
				{
					this.OnSTIDChanging(value);
					this.SendPropertyChanging();
					this._STID = value;
					this.SendPropertyChanged("STID");
					this.OnSTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ST
		{
			get
			{
				return this._ST;
			}
			set
			{
				if ((this._ST != value))
				{
					this.OnSTChanging(value);
					this.SendPropertyChanging();
					this._ST = value;
					this.SendPropertyChanged("ST");
					this.OnSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastTime
		{
			get
			{
				return this._LastTime;
			}
			set
			{
				if ((this._LastTime != value))
				{
					this.OnLastTimeChanging(value);
					this.SendPropertyChanging();
					this._LastTime = value;
					this.SendPropertyChanged("LastTime");
					this.OnLastTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dd", DbType="VarChar(200)")]
		public string dd
		{
			get
			{
				return this._dd;
			}
			set
			{
				if ((this._dd != value))
				{
					this.OnddChanging(value);
					this.SendPropertyChanging();
					this._dd = value;
					this.SendPropertyChanged("dd");
					this.OnddChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Msg")]
	public partial class T_Msg
	{
		
		private int _MsgID;
		
		private int _ST;
		
		private string _Msg;
		
		private System.DateTime _MsgTime;
		
		public T_Msg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MsgID
		{
			get
			{
				return this._MsgID;
			}
			set
			{
				if ((this._MsgID != value))
				{
					this._MsgID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST", DbType="Int NOT NULL")]
		public int ST
		{
			get
			{
				return this._ST;
			}
			set
			{
				if ((this._ST != value))
				{
					this._ST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Msg
		{
			get
			{
				return this._Msg;
			}
			set
			{
				if ((this._Msg != value))
				{
					this._Msg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgTime", DbType="DateTime NOT NULL")]
		public System.DateTime MsgTime
		{
			get
			{
				return this._MsgTime;
			}
			set
			{
				if ((this._MsgTime != value))
				{
					this._MsgTime = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
